apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-price-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: best-price-app
  template:
    metadata:
      labels:
        app: best-price-app
    spec:
      containers:
      - name: best-price-conatainer
        image: karthikvangari/second:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 3000  # Adjust the port as needed



