apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-price-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: best-price-app
  template:
    metadata:
      labels:
        app: best-price-app
    spec:
      containers:
      - name: best-price-conatainer
        image: karthikvangari/second:latest 
        ports:
        - containerPort: 3000  



