apiVersion: v1
kind: Service
metadata:
  name: best-price-service
spec:
  selector:
    app: best-price-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 3005  # Port your application is listening on
  type: LoadBalancer  # Expose the service externally

